-- Seed intencionalmente vazio.
--
-- A aplicação não cria contas, senhas ou papéis privilegiados por seed.
-- Cadastre o usuário pelo fluxo público e promova-o manualmente, conforme
-- documentado em backend/database/README.md.
--
-- Exemplo para executar depois de substituir o e-mail pelo usuário desejado:
-- UPDATE users SET role = 'professor' WHERE email = 'professor@example.com';
-- UPDATE users SET role = 'admin' WHERE email = 'admin@example.com';
